// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAIPh_M6CR0VjEsWSzampI_CYmU5rMOYA',
    appId: '1:647271817227:android:2d7681f3571b906679e70e',
    messagingSenderId: '647271817227',
    projectId: 'covoiturage-zygo',
    storageBucket: 'covoiturage-zygo.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO75BedUMf_NpedBeyZJMayyW-cjQ7eMI',
    appId: '1:647271817227:ios:b38a28256be09ea879e70e',
    messagingSenderId: '647271817227',
    projectId: 'covoiturage-zygo',
    storageBucket: 'covoiturage-zygo.firebasestorage.app',
    androidClientId: '647271817227-jgfr1ugmc6i15n4abt01q70mnqs4f4q1.apps.googleusercontent.com',
    iosClientId: '647271817227-k6dfth9b80cgsiqgbccmngmo9e4q0t03.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
